"""create surveys_simple_votes with pregunta_id

Revision ID: 069243ac8b97
Revises: 576722796663
Create Date: 2026-03-21 12:32:13.473189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '069243ac8b97'
down_revision: Union[str, Sequence[str], None] = '576722796663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys_simple_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('survey_simple_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcion_id'], ['surveys_simple_options.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['surveys_simple_questions.id'], ),
    sa.ForeignKeyConstraint(['survey_simple_id'], ['surveys_simple.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_simple_votes_id'), 'surveys_simple_votes', ['id'], unique=False)
    op.alter_column('surveys', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_surveys_simple_votes_id'), table_name='surveys_simple_votes')
    op.drop_table('surveys_simple_votes')
    # ### end Alembic commands ###
