"""add fecha_creacion to surveys

Revision ID: 576722796663
Revises: a0daf532feb9
Create Date: 2026-03-20 15:00:29.054463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '576722796663'
down_revision: Union[str, Sequence[str], None] = 'a0daf532feb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes_simple')
    op.drop_constraint(op.f('options_question_id_fkey'), 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.drop_constraint(op.f('questions_survey_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'surveys', ['survey_id'], ['id'])
    op.alter_column('surveys_simple', 'imagenes',
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="imagenes::jsonb"
    )

    op.alter_column('surveys_simple', 'videos',
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="videos::jsonb"
    )

    op.drop_column('surveys_simple', 'estado')
    op.create_foreign_key(None, 'surveys_simple_questions', 'surveys_simple', ['survey_simple_id'], ['id'])
    op.create_foreign_key(None, 'surveys_simple_votes', 'surveys_simple', ['survey_simple_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys_simple_votes', type_='foreignkey')
    op.drop_constraint(None, 'surveys_simple_questions', type_='foreignkey')
    op.add_column('surveys_simple', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('surveys_simple', 'videos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('surveys_simple', 'imagenes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_survey_id_fkey'), 'questions', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(op.f('options_question_id_fkey'), 'options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_table('votes_simple',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_simple_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pregunta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('votes_simple_pkey'))
    )
    # ### end Alembic commands ###
