"""add surveys_simple tables

Revision ID: b49719882549
Revises: 
Create Date: 2026-03-08 22:06:03.232886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49719882549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_surveys_id'), table_name='media_surveys')
    op.drop_table('media_surveys')
    op.drop_column('surveys', 'imagenes')
    op.drop_column('surveys', 'videos')
    op.drop_column('surveys', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('tipo', sa.VARCHAR(), server_default=sa.text("'simple'::character varying"), autoincrement=False, nullable=True))
    op.add_column('surveys', sa.Column('videos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('surveys', sa.Column('imagenes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('media_surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_surveys_pkey'))
    )
    op.create_index(op.f('ix_media_surveys_id'), 'media_surveys', ['id'], unique=False)
    # ### end Alembic commands ###
