"""add active, closed_at, closed_reason to surveys

Revision ID: c09f32608755
Revises: f25e6e7092b8
Create Date: 2026-05-30 15:12:34.328145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c09f32608755'
down_revision: Union[str, Sequence[str], None] = 'f25e6e7092b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('friends')
    op.alter_column('sponsor_transactions', 'beneficiario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sponsor_transactions', 'monto_dinero',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sponsor_transactions', 'puntos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sponsor_transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('survey_assignments', 'fecha_asignacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_survey_assignments_id'), 'survey_assignments', ['id'], unique=False)
    op.add_column('surveys', sa.Column('profesion', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('closed_reason', sa.String(), nullable=True))
    op.alter_column('surveys', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('surveys', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('usuarios', sa.Column('contrasena_hash', sa.String(), nullable=False))
    op.drop_column('usuarios', 'contraseña_hash')
    op.alter_column('wallet_movements', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wallet_movements', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('wallet_movements', 'monto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wallet_movements', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_movements', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('wallet_movements', 'monto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wallet_movements', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wallet_movements', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('usuarios', sa.Column('contraseña_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'contrasena_hash')
    op.alter_column('surveys', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('surveys', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('surveys', 'closed_reason')
    op.drop_column('surveys', 'closed_at')
    op.drop_column('surveys', 'profesion')
    op.drop_index(op.f('ix_survey_assignments_id'), table_name='survey_assignments')
    op.alter_column('survey_assignments', 'fecha_asignacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sponsor_transactions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sponsor_transactions', 'puntos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sponsor_transactions', 'monto_dinero',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sponsor_transactions', 'beneficiario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['usuarios.id'], name=op.f('fk_friend')),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('fk_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('friends_pkey')),
    sa.UniqueConstraint('user_id', 'friend_id', name=op.f('unique_friendship'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
